<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	</PropertyGroup>

    <ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<None Include="wwwroot\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Fleck" Version="1.2.0" />
    </ItemGroup>

</Project>
