/* eslint-disable prettier/prettier */
export const HEROES = [
    "Ana",
    "Anran",
    "Ashe",
    "Baptiste",
    "Bastion",
    "Brigitte",
    "Cassidy",
    "Dmon",
    "Doctrine",
    "Domina",
    "Doomfist",
    "Dva",
    "Echo",
    "Emre",
    "Freja",
    "Genji",
    "Hanzo",
    "Hazard",
    "Illari",
    "Jetpack Cat",
    "Junker Queen",
    "Juno",
    "Kiriko",
    "Lifeweaver",
    "Lucio",
    "Mauga",
    "Mei",
    "Mercy",
    "Mizuki",
    "Moira",
    "Orisa",
    "Pharah",
    "Ramattra",
    "Reaper",
    "Reinhardt",
    "Roadhog",
    "Shion",
    "Sierra",
    "Sigma",
    "Sojourn",
    "Soldier 76",
    "Sombra",
    "Symmetra",
    "Torbjorn",
    "Tracer",
    "Vendetta",
    "Venture",
    "Widowmaker",
    "Winston",
    "Wrecking Ball",
    "Wuyang", 
    "Zarya",
    "Zenyatta"
] as const;

export const MAPS = [
  'Aatlis',
  'Antarctic Peninsula',
  'Blizzard World',
  'Busan',
  'Circuit Royal',
  'Colosseo',
  'Dorado',
  'Eichenwalde',
  'Esperanca',
  'Havana',
  'Hollywood',
  'Ilios',
  'Junkertown',
  "King's Row",
  'Lijiang Tower',
  'Midtown',
  'Neon Junction',
  'Nepal',
  'New Junk City',
  'New Queens Street',
  'Numbani',
  'Oasis',
  'Paraiso',
  'Rialto',
  'Route 66',
  'Runasapi',
  'Samoa',
  'Shambali Monastery',
  'Suravasa',
  'Watchpoint Gibraltar',
  'Watchpoint Grimsvötn'
] as const;
